"""empty message

Revision ID: 781514ca1ada
Revises: 606d1cf32457
Create Date: 2020-08-23 16:54:12.372873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781514ca1ada'
down_revision = '606d1cf32457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Actor', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Actor', type_='unique')
    # ### end Alembic commands ###
