"""empty message

Revision ID: daaf819e8285
Revises: 781514ca1ada
Create Date: 2020-08-23 21:29:26.442349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daaf819e8285'
down_revision = '781514ca1ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Movie_Assignment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Movie_Assignment',
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['Actor.id'], name='Movie_Assignment_actor_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['Movie.id'], name='Movie_Assignment_movie_id_fkey'),
    sa.PrimaryKeyConstraint('movie_id', 'actor_id', name='Movie_Assignment_pkey')
    )
    # ### end Alembic commands ###
